"""create repository files table

Revision ID: 0b13a196ccc4
Revises: c5575b307fa1
Create Date: 2026-07-01 10:36:01.389986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b13a196ccc4'
down_revision: Union[str, Sequence[str], None] = 'c5575b307fa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository_files', sa.Column('file_name', sa.String(length=255), nullable=False))
    op.add_column('repository_files', sa.Column('relative_path', sa.String(length=1000), nullable=False))
    op.add_column('repository_files', sa.Column('absolute_path', sa.String(length=1000), nullable=False))
    op.add_column('repository_files', sa.Column('sha256', sa.String(length=64), nullable=False))
    op.add_column('repository_files', sa.Column('modified_time', sa.String(length=100), nullable=False))
    op.add_column('repository_files', sa.Column('is_parsed', sa.Boolean(), nullable=False))
    op.add_column('repository_files', sa.Column('parser_version', sa.String(length=30), nullable=False))
    op.add_column('repository_files', sa.Column('embedding_version', sa.String(length=30), nullable=False))
    op.alter_column('repository_files', 'language',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_column('repository_files', 'filename')
    op.drop_column('repository_files', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository_files', sa.Column('path', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.add_column('repository_files', sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('repository_files', 'language',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('repository_files', 'embedding_version')
    op.drop_column('repository_files', 'parser_version')
    op.drop_column('repository_files', 'is_parsed')
    op.drop_column('repository_files', 'modified_time')
    op.drop_column('repository_files', 'sha256')
    op.drop_column('repository_files', 'absolute_path')
    op.drop_column('repository_files', 'relative_path')
    op.drop_column('repository_files', 'file_name')
    # ### end Alembic commands ###
