"""create code embeddings table

Revision ID: 0e28c2c67862
Revises: f506d81ee4d4
Create Date: 2026-07-03 11:46:21.733163

"""
from typing import Sequence, Union

from alembic import op # type: ignore[import]
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector # type: ignore[import]


# revision identifiers, used by Alembic.
revision: str = '0e28c2c67862'
down_revision: Union[str, Sequence[str], None] = 'f506d81ee4d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_embeddings',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column(
        "embedding",
        Vector(768),
        nullable=True,
    ),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['code_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code_embeddings')
    # ### end Alembic commands ###
