"""add status column to repositories

Revision ID: 0e9c1fcb9779
Revises: 78ae48d5b629
Create Date: 2026-06-29 21:03:33.970330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e9c1fcb9779'
down_revision: Union[str, Sequence[str], None] = '78ae48d5b629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('status', sa.String(length=50), nullable=False))
    op.alter_column('repositories', 'local_path',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repositories', 'local_path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('repositories', 'status')
    # ### end Alembic commands ###
