"""make source symbol nullable

Revision ID: 23db3556ab01
Revises: e11970b3b42d
Create Date: 2026-07-02 13:54:28.582582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23db3556ab01'
down_revision: Union[str, Sequence[str], None] = 'e11970b3b42d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('code_dependencies', 'source_symbol_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('code_dependencies', 'source_symbol_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
