"""add repository summaries

Revision ID: 5c9c222bb98d
Revises: 77ee4c8d415d
Create Date: 2026-07-18 12:29:03.332173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9c222bb98d'
down_revision: Union[str, Sequence[str], None] = '77ee4c8d415d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_summaries',
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('framework', sa.String(), nullable=False),
    sa.Column('repository_type', sa.String(), nullable=False),
    sa.Column('entry_points', sa.Text(), nullable=False),
    sa.Column('api_routes', sa.Text(), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('total_classes', sa.Integer(), nullable=False),
    sa.Column('total_functions', sa.Integer(), nullable=False),
    sa.Column('total_modules', sa.Integer(), nullable=False),
    sa.Column('important_modules', sa.Text(), nullable=False),
    sa.Column('architecture', sa.Text(), nullable=False),
    sa.Column('execution_flow', sa.Text(), nullable=False),
    sa.Column('knowledge_card', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete="CASCADE", ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repository_summaries')
    # ### end Alembic commands ###
