"""add inherits to code symbols

Revision ID: 608f92cb8bdb
Revises: abbfc89f89b7
Create Date: 2026-07-01 19:52:14.609298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '608f92cb8bdb'
down_revision: Union[str, Sequence[str], None] = 'abbfc89f89b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_symbols', sa.Column('inherits', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_symbols', 'inherits')
    # ### end Alembic commands ###
