"""add symbol relationships

Revision ID: 77ee4c8d415d
Revises: 14a1e1f92de7
Create Date: 2026-07-16 10:48:39.783352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ee4c8d415d'
down_revision: Union[str, Sequence[str], None] = '14a1e1f92de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbol_relationships',
    sa.Column('from_symbol_id', sa.UUID(), nullable=False),
    sa.Column('to_symbol_id', sa.UUID(), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_symbol_id'], ['code_symbols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_symbol_id'], ['code_symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('symbol_relationships')
    # ### end Alembic commands ###
