"""create graph edges table

Revision ID: abbfc89f89b7
Revises: 0b13a196ccc4
Create Date: 2026-07-01 19:40:16.447934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abbfc89f89b7'
down_revision: Union[str, Sequence[str], None] = '0b13a196ccc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_edges',
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('source_symbol', sa.String(length=255), nullable=False),
    sa.Column('relation', sa.String(length=50), nullable=False),
    sa.Column('target_symbol', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graph_edges')
    # ### end Alembic commands ###
