"""repository processing status

Revision ID: b4ea0916c46f
Revises: 5c9c222bb98d
Create Date: 2026-07-26 17:08:35.060600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4ea0916c46f'
down_revision: Union[str, Sequence[str], None] = '5c9c222bb98d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "repositories",
        sa.Column(
            "progress",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

    op.add_column(
        "repositories",
        sa.Column(
            "current_stage",
            sa.String(length=255),
            nullable=False,
            server_default="Waiting...",
        ),
    )
    op.add_column(
        "repositories",
        sa.Column(
            "indexed_at",
            sa.DateTime(),
            nullable=True,
        ),
    )

    op.add_column(
        "repositories",
        sa.Column(
            "error_message",
            sa.String(length=500),
            nullable=True,
        ),
    )

    op.alter_column("repositories", "progress", server_default=None)
    op.alter_column("repositories", "current_stage", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'error_message')
    op.drop_column('repositories', 'indexed_at')
    op.drop_column('repositories', 'current_stage')
    op.drop_column('repositories', 'progress')
    # ### end Alembic commands ###
