"""parser v2

Revision ID: c5575b307fa1
Revises: e834d4f97a8b
Create Date: 2026-06-30 17:44:09.228109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5575b307fa1'
down_revision: Union[str, Sequence[str], None] = 'e834d4f97a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_symbols', sa.Column('decorators', sa.Text(), nullable=True))
    op.add_column('code_symbols', sa.Column('return_type', sa.String(length=255), nullable=True))
    op.add_column('code_symbols', sa.Column('parameters', sa.Text(), nullable=True))
    op.add_column('code_symbols', sa.Column('is_async', sa.Boolean(), nullable=False, server_default=sa.text("false"),),)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_symbols', 'is_async')
    op.drop_column('code_symbols', 'parameters')
    op.drop_column('code_symbols', 'return_type')
    op.drop_column('code_symbols', 'decorators')
    # ### end Alembic commands ###
