"""create code dependencies table

Revision ID: e11970b3b42d
Revises: 608f92cb8bdb
Create Date: 2026-07-02 13:33:47.821361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e11970b3b42d'
down_revision: Union[str, Sequence[str], None] = '608f92cb8bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_dependencies',
    sa.Column('source_symbol_id', sa.UUID(), nullable=False),
    sa.Column('target_name', sa.String(length=255), nullable=False),
    sa.Column('dependency_type', sa.String(length=255), nullable=False),
    sa.Column('source_file_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['repository_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_symbol_id'], ['code_symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code_dependencies')
    # ### end Alembic commands ###
