"""create code symbols table

Revision ID: e834d4f97a8b
Revises: 649f6aaa12a5
Create Date: 2026-06-30 12:23:44.543065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e834d4f97a8b'
down_revision: Union[str, Sequence[str], None] = '649f6aaa12a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_symbols',
    sa.Column('repository_file_id', sa.UUID(), nullable=False),
    sa.Column('symbol_name', sa.String(length=255), nullable=False),
    sa.Column('symbol_type', sa.String(length=50), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.Column('parent', sa.String(length=255), nullable=True),
    sa.Column('docstring', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_file_id'], ['repository_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code_symbols')
    # ### end Alembic commands ###
